#:schema https://www.schemastore.org/any.json
[default]
extend-ignore-re = [
  "(?m)^.*(#|//|;)\\s*codespell:ignore$",
  "(?ms)(#|//|;)\\s*codespell:ignore:start$.*(#|//|;)\\s*codespell:ignore:end$",
  "(?m)^.*(#|//|;)\\s*noqa$",
]
