#:schema https://www.schemastore.org/any.json
## Configuration for committed
##
## See <https://github.com/crate-ci/committed/blob/master/docs/reference.md>
style = "conventional"

line_length         = 80
merge_commit        = false
no_fixup            = false
subject_capitalized = false

allowed_types = [
  "fix",
  "feat",
  "chore",
  "docs",
  "style",
  "refactor",
  "perf",
  "test",
  "release",
]

# The author string is of the form `Name <email>`. We want to ignore all bots
# which typically are of the form `some-name[bot] <email>`.
ignore_author_re = "(?i)^.*\\[bot\\] <.*>$"
